# %%

import sys
from pathlib2 import Path
root_path = Path(__file__).resolve().parents[1]

if root_path not in sys.path:
    sys.path.insert(0, str(root_path))

DATA_BASE_PATH = root_path / 'data'
INTERIM_DATA_PATH = DATA_BASE_PATH / 'interim'
PROCESSED_DATA_PATH = DATA_BASE_PATH / 'processed'
RAW_DATA_PATH = DATA_BASE_PATH / 'raw'

MODEL_BASE_PATH = root_path / 'model'
ENC_MODEL_PATH = MODEL_BASE_PATH / 'encoded'
DIMRED_MODEL_PATH = MODEL_BASE_PATH / 'dimred'
# %%
CLAIM_CAT_COLS = ['CLAIM_TYPE', 'CLAIM_STATE', 'APPLICABLE_POLICY', 'DEALER_NUMBER', 'DEALER_CITY', 'DEALER_STATE', 'DEALER_COUNTRY',
                  'CAUSAL_REG_PART', 'FAULT_CODE', 'FAULT_LOCN', 'REG_PRODUCT_FAMILY_NAME', 'REG_SERIES_NAME', 'MODEL_NAME', 'REG_MODEL_CODE', 'VARIANT']

CLAIM_NUMBER = "CLAIM_NUMBER"
STD_LABOR_HRS = "STD_LABOR_HRS"
ADD_LABOR_HRS = "ADD_LABOR_HRS"
JOB_CODE = "JOB_CODE"
INS_PART_CODE = "INS_PART_CODE"
INS_PART_QNTY = "INS_PART_QNTY"
PART_TYPE = "PART_TYPE"
INS_PART_CODE = "INS_PART_CODE"
REG_PRODUCT_FAMILY_NAME = 'REG_PRODUCT_FAMILY_NAME'
